
# Autogenerated by mlir-tblgen; don't manually edit.

from ._ods_common import _cext as _ods_cext
from ._ods_common import (
    equally_sized_accessor as _ods_equally_sized_accessor,
    get_default_loc_context as _ods_get_default_loc_context,
    get_op_result_or_op_results as _get_op_result_or_op_results,
    get_op_result_or_value as _get_op_result_or_value,
    get_op_results_or_values as _get_op_results_or_values,
    segmented_accessor as _ods_segmented_accessor,
)
_ods_ir = _ods_cext.ir

import builtins
from typing import Sequence as _Sequence, Union as _Union


@_ods_cext.register_dialect
class _Dialect(_ods_ir.Dialect):
  DIALECT_NAMESPACE = "cuda"

@_ods_cext.register_operation(_Dialect)
class AddressOfOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.addressof"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, symname, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["symname"] = (symname if (
    isinstance(symname, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolRefAttr')) else
      _ods_ir.AttrBuilder.get('SymbolRefAttr')(symname, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def symname(self):
    return self.operation.attributes["symname"]

  @symname.setter
  def symname(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["symname"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def addressof(result, symname, *, loc=None, ip=None) -> _ods_ir.Value:
  return AddressOfOp(result=result, symname=symname, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class BinaryOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.binary"

  _ODS_REGIONS = (1, True)

  def __init__(self, sym_name, binary, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["sym_name"] = (sym_name if (
    isinstance(sym_name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolNameAttr')) else
      _ods_ir.AttrBuilder.get('SymbolNameAttr')(sym_name, context=_ods_context))
    attributes["binary"] = (binary if (
    isinstance(binary, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Builtin_DenseResourceElementsAttr')) else
      _ods_ir.AttrBuilder.get('Builtin_DenseResourceElementsAttr')(binary, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def sym_name(self):
    return self.operation.attributes["sym_name"]

  @sym_name.setter
  def sym_name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["sym_name"] = value

  @builtins.property
  def binary(self):
    return self.operation.attributes["binary"]

  @binary.setter
  def binary(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["binary"] = value

  @builtins.property
  def body(self):
    return self.regions[0]

def binary(sym_name, binary, *, loc=None, ip=None) -> _ods_ir.Operation:
  return BinaryOp(sym_name=sym_name, binary=binary, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class CastOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.cast"

  _ODS_REGIONS = (0, True)

  def __init__(self, dst, src, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(dst)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src(self):
    return self.operation.operands[0]

  @builtins.property
  def dst(self):
    return self.operation.results[0]

def cast(dst, src, *, loc=None, ip=None) -> _ods_ir.Value:
  return CastOp(dst=dst, src=src, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class DeviceSyncOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.device.sync"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def device_sync(cuda_result, *, loc=None, ip=None) -> _ods_ir.Value:
  return DeviceSyncOp(cuda_result=cuda_result, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class EventCreateOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.event.create"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, event, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    results.append(event)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def result(self):
    return self.operation.results[0]

  @builtins.property
  def event(self):
    return self.operation.results[1]

def event_create(result, event, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return EventCreateOp(result=result, event=event, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class EventDestroyOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.event.destroy"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, event, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(event))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def event(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def event_destroy(result, event, *, loc=None, ip=None) -> _ods_ir.Value:
  return EventDestroyOp(result=result, event=event, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class EventElapsedTimeOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.event.elapsed_time"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, elapsed_time, start_event, end_event, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(start_event))
    operands.append(_get_op_result_or_value(end_event))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    results.append(elapsed_time)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def start_event(self):
    return self.operation.operands[0]

  @builtins.property
  def end_event(self):
    return self.operation.operands[1]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

  @builtins.property
  def elapsed_time(self):
    return self.operation.results[1]

def event_elapsed_time(cuda_result, elapsed_time, start_event, end_event, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return EventElapsedTimeOp(cuda_result=cuda_result, elapsed_time=elapsed_time, start_event=start_event, end_event=end_event, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class EventRecordOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.event.record"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, event, *, stream=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(event))
    if stream is not None: operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def event(self):
    return self.operation.operands[0]

  @builtins.property
  def stream(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def event_record(result, event, *, stream=None, loc=None, ip=None) -> _ods_ir.Value:
  return EventRecordOp(result=result, event=event, stream=stream, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class FuncGetNameOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.func.get_name"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, name, kernel, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(kernel))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    results.append(name)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def kernel(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

  @builtins.property
  def name(self):
    return self.operation.results[1]

def func_get_name(result, name, kernel, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return FuncGetNameOp(result=result, name=name, kernel=kernel, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class FuncOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.func"

  _ODS_REGIONS = (1, True)

  def __init__(self, sym_name, function_type, *, arg_attrs=None, res_attrs=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["sym_name"] = (sym_name if (
    isinstance(sym_name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolNameAttr')) else
      _ods_ir.AttrBuilder.get('SymbolNameAttr')(sym_name, context=_ods_context))
    attributes["function_type"] = (function_type if (
    isinstance(function_type, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('anonymous_1240')) else
      _ods_ir.AttrBuilder.get('anonymous_1240')(function_type, context=_ods_context))
    if arg_attrs is not None: attributes["arg_attrs"] = (arg_attrs if (
        isinstance(arg_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(arg_attrs, context=_ods_context))
    if res_attrs is not None: attributes["res_attrs"] = (res_attrs if (
        isinstance(res_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(res_attrs, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def sym_name(self):
    return self.operation.attributes["sym_name"]

  @sym_name.setter
  def sym_name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["sym_name"] = value

  @builtins.property
  def function_type(self):
    return self.operation.attributes["function_type"]

  @function_type.setter
  def function_type(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["function_type"] = value

  @builtins.property
  def arg_attrs(self):
    if "arg_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["arg_attrs"]

  @arg_attrs.setter
  def arg_attrs(self, value):
    if value is not None:
      self.operation.attributes["arg_attrs"] = value
    elif "arg_attrs" in self.operation.attributes:
      del self.operation.attributes["arg_attrs"]

  @arg_attrs.deleter
  def arg_attrs(self):
    del self.operation.attributes["arg_attrs"]

  @builtins.property
  def res_attrs(self):
    if "res_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["res_attrs"]

  @res_attrs.setter
  def res_attrs(self, value):
    if value is not None:
      self.operation.attributes["res_attrs"] = value
    elif "res_attrs" in self.operation.attributes:
      del self.operation.attributes["res_attrs"]

  @res_attrs.deleter
  def res_attrs(self):
    del self.operation.attributes["res_attrs"]

  @builtins.property
  def body(self):
    return self.regions[0]

def func(sym_name, function_type, *, arg_attrs=None, res_attrs=None, loc=None, ip=None) -> _ods_ir.Operation:
  return FuncOp(sym_name=sym_name, function_type=function_type, arg_attrs=arg_attrs, res_attrs=res_attrs, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class GraphDestroyOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.graph.destroy"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, graph, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(graph))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def graph(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def graph_destroy(result, graph, *, loc=None, ip=None) -> _ods_ir.Value:
  return GraphDestroyOp(result=result, graph=graph, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class GraphExecDestroyOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.graph_exec.destroy"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, graph_exec, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(graph_exec))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def graph_exec(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def graph_exec_destroy(result, graph_exec, *, loc=None, ip=None) -> _ods_ir.Value:
  return GraphExecDestroyOp(result=result, graph_exec=graph_exec, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class GraphInstantiateOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.graph.instantiate"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, graph_exec, graph, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(graph))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    results.append(graph_exec)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def graph(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

  @builtins.property
  def graph_exec(self):
    return self.operation.results[1]

def graph_instantiate(result, graph_exec, graph, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return GraphInstantiateOp(result=result, graph_exec=graph_exec, graph=graph, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class GraphLaunchOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.graph.launch"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, graph_exec, stream, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(graph_exec))
    operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def graph_exec(self):
    return self.operation.operands[0]

  @builtins.property
  def stream(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def graph_launch(result, graph_exec, stream, *, loc=None, ip=None) -> _ods_ir.Value:
  return GraphLaunchOp(result=result, graph_exec=graph_exec, stream=stream, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class KernelOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.kernel"

  _ODS_REGIONS = (1, True)

  def __init__(self, sym_name, function_type, *, arg_attrs=None, res_attrs=None, cu_func_attrs=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["sym_name"] = (sym_name if (
    isinstance(sym_name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolNameAttr')) else
      _ods_ir.AttrBuilder.get('SymbolNameAttr')(sym_name, context=_ods_context))
    attributes["function_type"] = (function_type if (
    isinstance(function_type, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('anonymous_1240')) else
      _ods_ir.AttrBuilder.get('anonymous_1240')(function_type, context=_ods_context))
    if arg_attrs is not None: attributes["arg_attrs"] = (arg_attrs if (
        isinstance(arg_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(arg_attrs, context=_ods_context))
    if res_attrs is not None: attributes["res_attrs"] = (res_attrs if (
        isinstance(res_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(res_attrs, context=_ods_context))
    if cu_func_attrs is not None: attributes["cu_func_attrs"] = (cu_func_attrs if (
        isinstance(cu_func_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('Cuda_FuncAttrs')) else
          _ods_ir.AttrBuilder.get('Cuda_FuncAttrs')(cu_func_attrs, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def sym_name(self):
    return self.operation.attributes["sym_name"]

  @sym_name.setter
  def sym_name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["sym_name"] = value

  @builtins.property
  def function_type(self):
    return self.operation.attributes["function_type"]

  @function_type.setter
  def function_type(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["function_type"] = value

  @builtins.property
  def arg_attrs(self):
    if "arg_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["arg_attrs"]

  @arg_attrs.setter
  def arg_attrs(self, value):
    if value is not None:
      self.operation.attributes["arg_attrs"] = value
    elif "arg_attrs" in self.operation.attributes:
      del self.operation.attributes["arg_attrs"]

  @arg_attrs.deleter
  def arg_attrs(self):
    del self.operation.attributes["arg_attrs"]

  @builtins.property
  def res_attrs(self):
    if "res_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["res_attrs"]

  @res_attrs.setter
  def res_attrs(self, value):
    if value is not None:
      self.operation.attributes["res_attrs"] = value
    elif "res_attrs" in self.operation.attributes:
      del self.operation.attributes["res_attrs"]

  @res_attrs.deleter
  def res_attrs(self):
    del self.operation.attributes["res_attrs"]

  @builtins.property
  def cu_func_attrs(self):
    if "cu_func_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["cu_func_attrs"]

  @cu_func_attrs.setter
  def cu_func_attrs(self, value):
    if value is not None:
      self.operation.attributes["cu_func_attrs"] = value
    elif "cu_func_attrs" in self.operation.attributes:
      del self.operation.attributes["cu_func_attrs"]

  @cu_func_attrs.deleter
  def cu_func_attrs(self):
    del self.operation.attributes["cu_func_attrs"]

  @builtins.property
  def body(self):
    return self.regions[0]

def kernel(sym_name, function_type, *, arg_attrs=None, res_attrs=None, cu_func_attrs=None, loc=None, ip=None) -> _ods_ir.Operation:
  return KernelOp(sym_name=sym_name, function_type=function_type, arg_attrs=arg_attrs, res_attrs=res_attrs, cu_func_attrs=cu_func_attrs, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgAccessPolicyWindowOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.access_policy_window"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, base_ptr, hitProp, hitRatio, missProp, num_bytes, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(base_ptr))
    operands.append(_get_op_result_or_value(hitRatio))
    operands.append(_get_op_result_or_value(num_bytes))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["hitProp"] = (hitProp if (
    isinstance(hitProp, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('CudaAccessProperty')) else
      _ods_ir.AttrBuilder.get('CudaAccessProperty')(hitProp, context=_ods_context))
    attributes["missProp"] = (missProp if (
    isinstance(missProp, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('CudaAccessProperty')) else
      _ods_ir.AttrBuilder.get('CudaAccessProperty')(missProp, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def base_ptr(self):
    return self.operation.operands[1]

  @builtins.property
  def hitRatio(self):
    return self.operation.operands[2]

  @builtins.property
  def num_bytes(self):
    return self.operation.operands[3]

  @builtins.property
  def hitProp(self):
    return self.operation.attributes["hitProp"]

  @hitProp.setter
  def hitProp(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["hitProp"] = value

  @builtins.property
  def missProp(self):
    return self.operation.attributes["missProp"]

  @missProp.setter
  def missProp(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["missProp"] = value

def launch_cfg_access_policy_window(launch_cfg, base_ptr, hit_prop, hit_ratio, miss_prop, num_bytes, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgAccessPolicyWindowOp(launch_cfg=launch_cfg, base_ptr=base_ptr, hitProp=hit_prop, hitRatio=hit_ratio, missProp=miss_prop, num_bytes=num_bytes, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgClusterDimOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.cluster_dim"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, clusterDimX, clusterDimY, clusterDimZ, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(clusterDimX))
    operands.append(_get_op_result_or_value(clusterDimY))
    operands.append(_get_op_result_or_value(clusterDimZ))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def clusterDimX(self):
    return self.operation.operands[1]

  @builtins.property
  def clusterDimY(self):
    return self.operation.operands[2]

  @builtins.property
  def clusterDimZ(self):
    return self.operation.operands[3]

def launch_cfg_cluster_dim(launch_cfg, cluster_dim_x, cluster_dim_y, cluster_dim_z, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgClusterDimOp(launch_cfg=launch_cfg, clusterDimX=cluster_dim_x, clusterDimY=cluster_dim_y, clusterDimZ=cluster_dim_z, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgClusterSchedulingPolicyOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.cluster_scheduling_policy"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, policy, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["policy"] = (policy if (
    isinstance(policy, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('CudaClusterSchedulingPolicy')) else
      _ods_ir.AttrBuilder.get('CudaClusterSchedulingPolicy')(policy, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def policy(self):
    return self.operation.attributes["policy"]

  @policy.setter
  def policy(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["policy"] = value

def launch_cfg_cluster_scheduling_policy(launch_cfg, policy, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgClusterSchedulingPolicyOp(launch_cfg=launch_cfg, policy=policy, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgCooperativeOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.cooperative"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, cooperative, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(cooperative))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def cooperative(self):
    return self.operation.operands[1]

def launch_cfg_cooperative(launch_cfg, cooperative, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgCooperativeOp(launch_cfg=launch_cfg, cooperative=cooperative, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgCreateOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.create"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, maxNumAttrs, blockDimX, blockDimY, blockDimZ, dynamicSmemBytes, gridDimX, gridDimY, gridDimZ, stream, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(blockDimX))
    operands.append(_get_op_result_or_value(blockDimY))
    operands.append(_get_op_result_or_value(blockDimZ))
    operands.append(_get_op_result_or_value(dynamicSmemBytes))
    operands.append(_get_op_result_or_value(gridDimX))
    operands.append(_get_op_result_or_value(gridDimY))
    operands.append(_get_op_result_or_value(gridDimZ))
    operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["maxNumAttrs"] = (maxNumAttrs if (
    isinstance(maxNumAttrs, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Builtin_IntegerAttr')) else
      _ods_ir.AttrBuilder.get('Builtin_IntegerAttr')(maxNumAttrs, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def blockDimX(self):
    return self.operation.operands[0]

  @builtins.property
  def blockDimY(self):
    return self.operation.operands[1]

  @builtins.property
  def blockDimZ(self):
    return self.operation.operands[2]

  @builtins.property
  def dynamicSmemBytes(self):
    return self.operation.operands[3]

  @builtins.property
  def gridDimX(self):
    return self.operation.operands[4]

  @builtins.property
  def gridDimY(self):
    return self.operation.operands[5]

  @builtins.property
  def gridDimZ(self):
    return self.operation.operands[6]

  @builtins.property
  def stream(self):
    return self.operation.operands[7]

  @builtins.property
  def maxNumAttrs(self):
    return self.operation.attributes["maxNumAttrs"]

  @maxNumAttrs.setter
  def maxNumAttrs(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["maxNumAttrs"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def launch_cfg_create(result, max_num_attrs, block_dim_x, block_dim_y, block_dim_z, dynamic_smem_bytes, grid_dim_x, grid_dim_y, grid_dim_z, stream, *, loc=None, ip=None) -> _ods_ir.Value:
  return LaunchCfgCreateOp(result=result, maxNumAttrs=max_num_attrs, blockDimX=block_dim_x, blockDimY=block_dim_y, blockDimZ=block_dim_z, dynamicSmemBytes=dynamic_smem_bytes, gridDimX=grid_dim_x, gridDimY=grid_dim_y, gridDimZ=grid_dim_z, stream=stream, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class LaunchCfgDeviceUpdatableKernelNodeOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.device_updatable_kernel_node"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, devNode, deviceUpdatable, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(devNode))
    operands.append(_get_op_result_or_value(deviceUpdatable))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def devNode(self):
    return self.operation.operands[1]

  @builtins.property
  def deviceUpdatable(self):
    return self.operation.operands[2]

def launch_cfg_device_updatable_kernel_node(launch_cfg, dev_node, device_updatable, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgDeviceUpdatableKernelNodeOp(launch_cfg=launch_cfg, devNode=dev_node, deviceUpdatable=device_updatable, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgLaunchCompletionEventOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.launch_completion_event"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, event, flags, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(event))
    operands.append(_get_op_result_or_value(flags))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def event(self):
    return self.operation.operands[1]

  @builtins.property
  def flags(self):
    return self.operation.operands[2]

def launch_cfg_launch_completion_event(launch_cfg, event, flags, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgLaunchCompletionEventOp(launch_cfg=launch_cfg, event=event, flags=flags, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgMemSyncDomainMapOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.mem_sync_domain_map"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, domain_default, domain_remote, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(domain_default))
    operands.append(_get_op_result_or_value(domain_remote))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def domain_default(self):
    return self.operation.operands[1]

  @builtins.property
  def domain_remote(self):
    return self.operation.operands[2]

def launch_cfg_mem_sync_domain_map(launch_cfg, domain_default, domain_remote, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgMemSyncDomainMapOp(launch_cfg=launch_cfg, domain_default=domain_default, domain_remote=domain_remote, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgMemSyncDomainOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.mem_sync_domain"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, memSyncDomain, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["memSyncDomain"] = (memSyncDomain if (
    isinstance(memSyncDomain, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('CudaLaunchMemSyncDomain')) else
      _ods_ir.AttrBuilder.get('CudaLaunchMemSyncDomain')(memSyncDomain, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def memSyncDomain(self):
    return self.operation.attributes["memSyncDomain"]

  @memSyncDomain.setter
  def memSyncDomain(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["memSyncDomain"] = value

def launch_cfg_mem_sync_domain(launch_cfg, mem_sync_domain, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgMemSyncDomainOp(launch_cfg=launch_cfg, memSyncDomain=mem_sync_domain, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgNvlinkUtilCentricSchedulingOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.nvlink_util_centric_scheduling"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, nvlinkSchedulingEnabled, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(nvlinkSchedulingEnabled))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def nvlinkSchedulingEnabled(self):
    return self.operation.operands[1]

def launch_cfg_nvlink_util_centric_scheduling(launch_cfg, nvlink_scheduling_enabled, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgNvlinkUtilCentricSchedulingOp(launch_cfg=launch_cfg, nvlinkSchedulingEnabled=nvlink_scheduling_enabled, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgPreferredClusterDimOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.preferred_cluster_dim"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, preferredClusterDimX, preferredClusterDimY, preferredClusterDimZ, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(preferredClusterDimX))
    operands.append(_get_op_result_or_value(preferredClusterDimY))
    operands.append(_get_op_result_or_value(preferredClusterDimZ))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def preferredClusterDimX(self):
    return self.operation.operands[1]

  @builtins.property
  def preferredClusterDimY(self):
    return self.operation.operands[2]

  @builtins.property
  def preferredClusterDimZ(self):
    return self.operation.operands[3]

def launch_cfg_preferred_cluster_dim(launch_cfg, preferred_cluster_dim_x, preferred_cluster_dim_y, preferred_cluster_dim_z, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgPreferredClusterDimOp(launch_cfg=launch_cfg, preferredClusterDimX=preferred_cluster_dim_x, preferredClusterDimY=preferred_cluster_dim_y, preferredClusterDimZ=preferred_cluster_dim_z, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgPrintOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.print"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

def launch_cfg_print(launch_cfg, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgPrintOp(launch_cfg=launch_cfg, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgPriorityOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.priority"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, priority, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(priority))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def priority(self):
    return self.operation.operands[1]

def launch_cfg_priority(launch_cfg, priority, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgPriorityOp(launch_cfg=launch_cfg, priority=priority, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgProgrammaticEventOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.programmatic_event"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, event, flags, triggerAtBlockStart, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(event))
    operands.append(_get_op_result_or_value(flags))
    operands.append(_get_op_result_or_value(triggerAtBlockStart))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def event(self):
    return self.operation.operands[1]

  @builtins.property
  def flags(self):
    return self.operation.operands[2]

  @builtins.property
  def triggerAtBlockStart(self):
    return self.operation.operands[3]

def launch_cfg_programmatic_event(launch_cfg, event, flags, trigger_at_block_start, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgProgrammaticEventOp(launch_cfg=launch_cfg, event=event, flags=flags, triggerAtBlockStart=trigger_at_block_start, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgProgrammaticStreamSerializationAllowedOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.programmatic_stream_serialization_allowed"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, programmaticStreamSerializationAllowed, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(programmaticStreamSerializationAllowed))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def programmaticStreamSerializationAllowed(self):
    return self.operation.operands[1]

def launch_cfg_programmatic_stream_serialization_allowed(launch_cfg, programmatic_stream_serialization_allowed, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgProgrammaticStreamSerializationAllowedOp(launch_cfg=launch_cfg, programmaticStreamSerializationAllowed=programmatic_stream_serialization_allowed, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgSharedMemCarveoutOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.shared_mem_carveout"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, sharedMemCarveout, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.append(_get_op_result_or_value(sharedMemCarveout))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def sharedMemCarveout(self):
    return self.operation.operands[1]

def launch_cfg_shared_mem_carveout(launch_cfg, shared_mem_carveout, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgSharedMemCarveoutOp(launch_cfg=launch_cfg, sharedMemCarveout=shared_mem_carveout, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchCfgSyncPolicyOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_cfg.sync_policy"

  _ODS_REGIONS = (0, True)

  def __init__(self, launch_cfg, syncPolicy, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["syncPolicy"] = (syncPolicy if (
    isinstance(syncPolicy, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('CudaSynchronizationPolicy')) else
      _ods_ir.AttrBuilder.get('CudaSynchronizationPolicy')(syncPolicy, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def syncPolicy(self):
    return self.operation.attributes["syncPolicy"]

  @syncPolicy.setter
  def syncPolicy(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["syncPolicy"] = value

def launch_cfg_sync_policy(launch_cfg, sync_policy, *, loc=None, ip=None) -> _ods_ir.Operation:
  return LaunchCfgSyncPolicyOp(launch_cfg=launch_cfg, syncPolicy=sync_policy, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class LaunchExOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_ex"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, callee, launch_cfg, inputs, *, arg_attrs=None, res_attrs=None, assume_kernel_attr=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(launch_cfg))
    operands.extend(_get_op_results_or_values(inputs))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["callee"] = (callee if (
    isinstance(callee, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolRefAttr')) else
      _ods_ir.AttrBuilder.get('SymbolRefAttr')(callee, context=_ods_context))
    if arg_attrs is not None: attributes["arg_attrs"] = (arg_attrs if (
        isinstance(arg_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(arg_attrs, context=_ods_context))
    if res_attrs is not None: attributes["res_attrs"] = (res_attrs if (
        isinstance(res_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(res_attrs, context=_ods_context))
    if assume_kernel_attr is not None: attributes["assume_kernel_attr"] = (assume_kernel_attr if (
        isinstance(assume_kernel_attr, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('Cuda_AssumeKernelAttr')) else
          _ods_ir.AttrBuilder.get('Cuda_AssumeKernelAttr')(assume_kernel_attr, context=_ods_context))
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def launch_cfg(self):
    return self.operation.operands[0]

  @builtins.property
  def inputs(self):
    _ods_variadic_group_length = len(self.operation.operands) - 2 + 1
    return self.operation.operands[1:1 + _ods_variadic_group_length]

  @builtins.property
  def callee(self):
    return self.operation.attributes["callee"]

  @callee.setter
  def callee(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["callee"] = value

  @builtins.property
  def arg_attrs(self):
    if "arg_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["arg_attrs"]

  @arg_attrs.setter
  def arg_attrs(self, value):
    if value is not None:
      self.operation.attributes["arg_attrs"] = value
    elif "arg_attrs" in self.operation.attributes:
      del self.operation.attributes["arg_attrs"]

  @arg_attrs.deleter
  def arg_attrs(self):
    del self.operation.attributes["arg_attrs"]

  @builtins.property
  def res_attrs(self):
    if "res_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["res_attrs"]

  @res_attrs.setter
  def res_attrs(self, value):
    if value is not None:
      self.operation.attributes["res_attrs"] = value
    elif "res_attrs" in self.operation.attributes:
      del self.operation.attributes["res_attrs"]

  @res_attrs.deleter
  def res_attrs(self):
    del self.operation.attributes["res_attrs"]

  @builtins.property
  def assume_kernel_attr(self):
    if "assume_kernel_attr" not in self.operation.attributes:
      return None
    return self.operation.attributes["assume_kernel_attr"]

  @assume_kernel_attr.setter
  def assume_kernel_attr(self, value):
    if value is not None:
      self.operation.attributes["assume_kernel_attr"] = value
    elif "assume_kernel_attr" in self.operation.attributes:
      del self.operation.attributes["assume_kernel_attr"]

  @assume_kernel_attr.deleter
  def assume_kernel_attr(self):
    del self.operation.attributes["assume_kernel_attr"]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def launch_ex(cuda_result, callee, launch_cfg, inputs, *, arg_attrs=None, res_attrs=None, assume_kernel_attr=None, loc=None, ip=None) -> _ods_ir.Value:
  return LaunchExOp(cuda_result=cuda_result, callee=callee, launch_cfg=launch_cfg, inputs=inputs, arg_attrs=arg_attrs, res_attrs=res_attrs, assume_kernel_attr=assume_kernel_attr, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class LaunchKernelOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch_kernel"

  _ODS_OPERAND_SEGMENTS = [1,-1,-1,1,1,1,]

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, kernel, grid, block, dynamicSmem, cudaStream, kernel_args, *, arg_attrs=None, res_attrs=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(kernel))
    operands.append(_get_op_results_or_values(grid))
    operands.append(_get_op_results_or_values(block))
    operands.append(_get_op_result_or_value(dynamicSmem))
    operands.append(_get_op_result_or_value(cudaStream))
    operands.append(_get_op_result_or_value(kernel_args))
    _ods_context = _ods_get_default_loc_context(loc)
    if arg_attrs is not None: attributes["arg_attrs"] = (arg_attrs if (
        isinstance(arg_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(arg_attrs, context=_ods_context))
    if res_attrs is not None: attributes["res_attrs"] = (res_attrs if (
        isinstance(res_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(res_attrs, context=_ods_context))
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def kernel(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 0)
    return operand_range[0]

  @builtins.property
  def grid(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 1)
    return operand_range

  @builtins.property
  def block(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 2)
    return operand_range

  @builtins.property
  def dynamicSmem(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 3)
    return operand_range[0]

  @builtins.property
  def cudaStream(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 4)
    return operand_range[0]

  @builtins.property
  def kernel_args(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 5)
    return operand_range[0]

  @builtins.property
  def arg_attrs(self):
    if "arg_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["arg_attrs"]

  @arg_attrs.setter
  def arg_attrs(self, value):
    if value is not None:
      self.operation.attributes["arg_attrs"] = value
    elif "arg_attrs" in self.operation.attributes:
      del self.operation.attributes["arg_attrs"]

  @arg_attrs.deleter
  def arg_attrs(self):
    del self.operation.attributes["arg_attrs"]

  @builtins.property
  def res_attrs(self):
    if "res_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["res_attrs"]

  @res_attrs.setter
  def res_attrs(self, value):
    if value is not None:
      self.operation.attributes["res_attrs"] = value
    elif "res_attrs" in self.operation.attributes:
      del self.operation.attributes["res_attrs"]

  @res_attrs.deleter
  def res_attrs(self):
    del self.operation.attributes["res_attrs"]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def launch_kernel(cuda_result, kernel, grid, block, dynamic_smem, cuda_stream, kernel_args, *, arg_attrs=None, res_attrs=None, loc=None, ip=None) -> _ods_ir.Value:
  return LaunchKernelOp(cuda_result=cuda_result, kernel=kernel, grid=grid, block=block, dynamicSmem=dynamic_smem, cudaStream=cuda_stream, kernel_args=kernel_args, arg_attrs=arg_attrs, res_attrs=res_attrs, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class LaunchOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.launch"

  _ODS_OPERAND_SEGMENTS = [-1,-1,1,1,-1,]

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, callee, grid, block, dynamicSmem, cudaStream, inputs, *, arg_attrs=None, res_attrs=None, assume_kernel_attr=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_results_or_values(grid))
    operands.append(_get_op_results_or_values(block))
    operands.append(_get_op_result_or_value(dynamicSmem))
    operands.append(_get_op_result_or_value(cudaStream))
    operands.append(_get_op_results_or_values(inputs))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["callee"] = (callee if (
    isinstance(callee, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolRefAttr')) else
      _ods_ir.AttrBuilder.get('SymbolRefAttr')(callee, context=_ods_context))
    if arg_attrs is not None: attributes["arg_attrs"] = (arg_attrs if (
        isinstance(arg_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(arg_attrs, context=_ods_context))
    if res_attrs is not None: attributes["res_attrs"] = (res_attrs if (
        isinstance(res_attrs, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('DictArrayAttr')) else
          _ods_ir.AttrBuilder.get('DictArrayAttr')(res_attrs, context=_ods_context))
    if assume_kernel_attr is not None: attributes["assume_kernel_attr"] = (assume_kernel_attr if (
        isinstance(assume_kernel_attr, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('Cuda_AssumeKernelAttr')) else
          _ods_ir.AttrBuilder.get('Cuda_AssumeKernelAttr')(assume_kernel_attr, context=_ods_context))
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def grid(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 0)
    return operand_range

  @builtins.property
  def block(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 1)
    return operand_range

  @builtins.property
  def dynamicSmem(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 2)
    return operand_range[0]

  @builtins.property
  def cudaStream(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 3)
    return operand_range[0]

  @builtins.property
  def inputs(self):
    operand_range = _ods_segmented_accessor(
         self.operation.operands,
         self.operation.attributes["operandSegmentSizes"], 4)
    return operand_range

  @builtins.property
  def callee(self):
    return self.operation.attributes["callee"]

  @callee.setter
  def callee(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["callee"] = value

  @builtins.property
  def arg_attrs(self):
    if "arg_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["arg_attrs"]

  @arg_attrs.setter
  def arg_attrs(self, value):
    if value is not None:
      self.operation.attributes["arg_attrs"] = value
    elif "arg_attrs" in self.operation.attributes:
      del self.operation.attributes["arg_attrs"]

  @arg_attrs.deleter
  def arg_attrs(self):
    del self.operation.attributes["arg_attrs"]

  @builtins.property
  def res_attrs(self):
    if "res_attrs" not in self.operation.attributes:
      return None
    return self.operation.attributes["res_attrs"]

  @res_attrs.setter
  def res_attrs(self, value):
    if value is not None:
      self.operation.attributes["res_attrs"] = value
    elif "res_attrs" in self.operation.attributes:
      del self.operation.attributes["res_attrs"]

  @res_attrs.deleter
  def res_attrs(self):
    del self.operation.attributes["res_attrs"]

  @builtins.property
  def assume_kernel_attr(self):
    if "assume_kernel_attr" not in self.operation.attributes:
      return None
    return self.operation.attributes["assume_kernel_attr"]

  @assume_kernel_attr.setter
  def assume_kernel_attr(self, value):
    if value is not None:
      self.operation.attributes["assume_kernel_attr"] = value
    elif "assume_kernel_attr" in self.operation.attributes:
      del self.operation.attributes["assume_kernel_attr"]

  @assume_kernel_attr.deleter
  def assume_kernel_attr(self):
    del self.operation.attributes["assume_kernel_attr"]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def launch(cuda_result, callee, grid, block, dynamic_smem, cuda_stream, inputs, *, arg_attrs=None, res_attrs=None, assume_kernel_attr=None, loc=None, ip=None) -> _ods_ir.Value:
  return LaunchOp(cuda_result=cuda_result, callee=callee, grid=grid, block=block, dynamicSmem=dynamic_smem, cudaStream=cuda_stream, inputs=inputs, arg_attrs=arg_attrs, res_attrs=res_attrs, assume_kernel_attr=assume_kernel_attr, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class LibraryGetKernelOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.library.get_kernel"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, kernel, library, kernel_name, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(library))
    operands.append(_get_op_result_or_value(kernel_name))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    results.append(kernel)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def library(self):
    return self.operation.operands[0]

  @builtins.property
  def kernel_name(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

  @builtins.property
  def kernel(self):
    return self.operation.results[1]

def library_get_kernel(result, kernel, library, kernel_name, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return LibraryGetKernelOp(result=result, kernel=kernel, library=library, kernel_name=kernel_name, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class LibraryLoadDataOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.library.load_data"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, library, data, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(data))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    results.append(library)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def data(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

  @builtins.property
  def library(self):
    return self.operation.results[1]

def library_load_data(result, library, data, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return LibraryLoadDataOp(result=result, library=library, data=data, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class LibraryUnloadOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.library.unload"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, library, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(library))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def library(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def library_unload(result, library, *, loc=None, ip=None) -> _ods_ir.Value:
  return LibraryUnloadOp(result=result, library=library, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MemoryAllocAsyncOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.alloc_async"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, bytes, stream, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(bytes))
    operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def bytes(self):
    return self.operation.operands[0]

  @builtins.property
  def stream(self):
    return self.operation.operands[1]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[1]

def memory_alloc_async(cuda_result, ptr, bytes, stream, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return MemoryAllocAsyncOp(cuda_result=cuda_result, ptr=ptr, bytes=bytes, stream=stream, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class MemoryAllocHostOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.alloc_host"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, bytes, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(bytes))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def bytes(self):
    return self.operation.operands[0]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[1]

def memory_alloc_host(cuda_result, ptr, bytes, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return MemoryAllocHostOp(cuda_result=cuda_result, ptr=ptr, bytes=bytes, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class MemoryAllocManagedOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.alloc_managed"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, bytes, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(bytes))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def bytes(self):
    return self.operation.operands[0]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[1]

def memory_alloc_managed(cuda_result, ptr, bytes, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return MemoryAllocManagedOp(cuda_result=cuda_result, ptr=ptr, bytes=bytes, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class MemoryAllocOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.alloc"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, bytes, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(bytes))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def bytes(self):
    return self.operation.operands[0]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[1]

def memory_alloc(cuda_result, ptr, bytes, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return MemoryAllocOp(cuda_result=cuda_result, ptr=ptr, bytes=bytes, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class MemoryCopyAsyncOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.copy_async"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, src, dst, bytes, kind, *, stream=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src))
    operands.append(_get_op_result_or_value(dst))
    operands.append(_get_op_result_or_value(bytes))
    if stream is not None: operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["kind"] = (kind if (
    isinstance(kind, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('CudaMemcpyKindEnum')) else
      _ods_ir.AttrBuilder.get('CudaMemcpyKindEnum')(kind, context=_ods_context))
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src(self):
    return self.operation.operands[0]

  @builtins.property
  def dst(self):
    return self.operation.operands[1]

  @builtins.property
  def bytes(self):
    return self.operation.operands[2]

  @builtins.property
  def stream(self):
    return None if len(self.operation.operands) < 4 else self.operation.operands[3]

  @builtins.property
  def kind(self):
    return self.operation.attributes["kind"]

  @kind.setter
  def kind(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["kind"] = value

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def memory_copy_async(cuda_result, src, dst, bytes, kind, *, stream=None, loc=None, ip=None) -> _ods_ir.Value:
  return MemoryCopyAsyncOp(cuda_result=cuda_result, src=src, dst=dst, bytes=bytes, kind=kind, stream=stream, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MemoryCopyOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.copy"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, src, dst, bytes, kind, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src))
    operands.append(_get_op_result_or_value(dst))
    operands.append(_get_op_result_or_value(bytes))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["kind"] = (kind if (
    isinstance(kind, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('CudaMemcpyKindEnum')) else
      _ods_ir.AttrBuilder.get('CudaMemcpyKindEnum')(kind, context=_ods_context))
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src(self):
    return self.operation.operands[0]

  @builtins.property
  def dst(self):
    return self.operation.operands[1]

  @builtins.property
  def bytes(self):
    return self.operation.operands[2]

  @builtins.property
  def kind(self):
    return self.operation.attributes["kind"]

  @kind.setter
  def kind(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["kind"] = value

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def memory_copy(cuda_result, src, dst, bytes, kind, *, loc=None, ip=None) -> _ods_ir.Value:
  return MemoryCopyOp(cuda_result=cuda_result, src=src, dst=dst, bytes=bytes, kind=kind, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MemoryFreeAsyncOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.free_async"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, stream, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def stream(self):
    return self.operation.operands[1]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def memory_free_async(cuda_result, ptr, stream, *, loc=None, ip=None) -> _ods_ir.Value:
  return MemoryFreeAsyncOp(cuda_result=cuda_result, ptr=ptr, stream=stream, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MemoryFreeHostOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.free_host"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def memory_free_host(cuda_result, ptr, *, loc=None, ip=None) -> _ods_ir.Value:
  return MemoryFreeHostOp(cuda_result=cuda_result, ptr=ptr, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MemoryFreeOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.free"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def memory_free(cuda_result, ptr, *, loc=None, ip=None) -> _ods_ir.Value:
  return MemoryFreeOp(cuda_result=cuda_result, ptr=ptr, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MemorySetAsyncOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.set_async"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, value, bytes, *, stream=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    operands.append(_get_op_result_or_value(value))
    operands.append(_get_op_result_or_value(bytes))
    if stream is not None: operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def value(self):
    return self.operation.operands[1]

  @builtins.property
  def bytes(self):
    return self.operation.operands[2]

  @builtins.property
  def stream(self):
    return None if len(self.operation.operands) < 4 else self.operation.operands[3]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def memory_set_async(cuda_result, ptr, value, bytes, *, stream=None, loc=None, ip=None) -> _ods_ir.Value:
  return MemorySetAsyncOp(cuda_result=cuda_result, ptr=ptr, value=value, bytes=bytes, stream=stream, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class MemorySetOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.memory.set"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, ptr, value, bytes, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    operands.append(_get_op_result_or_value(value))
    operands.append(_get_op_result_or_value(bytes))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def value(self):
    return self.operation.operands[1]

  @builtins.property
  def bytes(self):
    return self.operation.operands[2]

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

def memory_set(cuda_result, ptr, value, bytes, *, loc=None, ip=None) -> _ods_ir.Value:
  return MemorySetOp(cuda_result=cuda_result, ptr=ptr, value=value, bytes=bytes, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class OccupancyMaxActiveBlocks(_ods_ir.OpView):
  OPERATION_NAME = "cuda.occupancy_max_active_blocks_per_multiprocessor"

  _ODS_REGIONS = (0, True)

  def __init__(self, res, num_blocks, func, block_size, dynamic_smem_size, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(block_size))
    operands.append(_get_op_result_or_value(dynamic_smem_size))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["func"] = (func if (
    isinstance(func, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolRefAttr')) else
      _ods_ir.AttrBuilder.get('SymbolRefAttr')(func, context=_ods_context))
    results.append(res)
    results.append(num_blocks)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def block_size(self):
    return self.operation.operands[0]

  @builtins.property
  def dynamic_smem_size(self):
    return self.operation.operands[1]

  @builtins.property
  def func(self):
    return self.operation.attributes["func"]

  @func.setter
  def func(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["func"] = value

  @builtins.property
  def res(self):
    return self.operation.results[0]

  @builtins.property
  def num_blocks(self):
    return self.operation.results[1]

def occupancy_max_active_blocks_per_multiprocessor(res, num_blocks, func, block_size, dynamic_smem_size, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return OccupancyMaxActiveBlocks(res=res, num_blocks=num_blocks, func=func, block_size=block_size, dynamic_smem_size=dynamic_smem_size, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class ProfilerStart(_ods_ir.OpView):
  OPERATION_NAME = "cuda.profiler.start"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def result(self):
    return self.operation.results[0]

def profiler_start(result, *, loc=None, ip=None) -> _ods_ir.Value:
  return ProfilerStart(result=result, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class ProfilerStop(_ods_ir.OpView):
  OPERATION_NAME = "cuda.profiler.stop"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def result(self):
    return self.operation.results[0]

def profiler_stop(result, *, loc=None, ip=None) -> _ods_ir.Value:
  return ProfilerStop(result=result, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class ResultAssertSuccessOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.result.assert_success"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(cuda_result))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def cuda_result(self):
    return self.operation.operands[0]

def result_assert_success(cuda_result, *, loc=None, ip=None) -> _ods_ir.Operation:
  return ResultAssertSuccessOp(cuda_result=cuda_result, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ResultFailedOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.result.failed"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

def result_failed(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ResultFailedOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ResultPrintOnErrorOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.result.print_on_error"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(cuda_result))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def cuda_result(self):
    return self.operation.operands[0]

def result_print_on_error(cuda_result, *, loc=None, ip=None) -> _ods_ir.Operation:
  return ResultPrintOnErrorOp(cuda_result=cuda_result, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ResultSucceededOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.result.succeeded"

  _ODS_REGIONS = (0, True)

  def __init__(self, success, cuda_result, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(cuda_result))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(success)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def cuda_result(self):
    return self.operation.operands[0]

  @builtins.property
  def success(self):
    return self.operation.results[0]

def result_succeeded(success, cuda_result, *, loc=None, ip=None) -> _ods_ir.Value:
  return ResultSucceededOp(success=success, cuda_result=cuda_result, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class ReturnIfErrorOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.return_if_error"

  _ODS_REGIONS = (0, True)

  def __init__(self, inputs, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(inputs))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def inputs(self):
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

def return_if_error(inputs, *, loc=None, ip=None) -> _ods_ir.Operation:
  return ReturnIfErrorOp(inputs=inputs, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ReturnOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.return"

  _ODS_REGIONS = (0, True)

  def __init__(self, inputs, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(inputs))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def inputs(self):
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

def return_(inputs, *, loc=None, ip=None) -> _ods_ir.Operation:
  return ReturnOp(inputs=inputs, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class StreamAddCallbackOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.stream.add_callback"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, stream, callback, user_data, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(stream))
    operands.append(_get_op_result_or_value(user_data))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["callback"] = (callback if (
    isinstance(callback, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('FlatSymbolRefAttr')) else
      _ods_ir.AttrBuilder.get('FlatSymbolRefAttr')(callback, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def stream(self):
    return self.operation.operands[0]

  @builtins.property
  def user_data(self):
    return self.operation.operands[1]

  @builtins.property
  def callback(self):
    return self.operation.attributes["callback"]

  @callback.setter
  def callback(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["callback"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def stream_add_callback(result, stream, callback, user_data, *, loc=None, ip=None) -> _ods_ir.Value:
  return StreamAddCallbackOp(result=result, stream=stream, callback=callback, user_data=user_data, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class StreamBeginCaptureOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.stream.begin_capture"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, stream, mode, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["mode"] = (mode if (
    isinstance(mode, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('CudaStreamCaptureModeEnum')) else
      _ods_ir.AttrBuilder.get('CudaStreamCaptureModeEnum')(mode, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def stream(self):
    return self.operation.operands[0]

  @builtins.property
  def mode(self):
    return self.operation.attributes["mode"]

  @mode.setter
  def mode(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["mode"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def stream_begin_capture(result, stream, mode, *, loc=None, ip=None) -> _ods_ir.Value:
  return StreamBeginCaptureOp(result=result, stream=stream, mode=mode, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class StreamCreateOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.stream.create"

  _ODS_REGIONS = (0, True)

  def __init__(self, cuda_result, stream, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(cuda_result)
    results.append(stream)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def cuda_result(self):
    return self.operation.results[0]

  @builtins.property
  def stream(self):
    return self.operation.results[1]

def stream_create(cuda_result, stream, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return StreamCreateOp(cuda_result=cuda_result, stream=stream, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class StreamDestroyOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.stream.destroy"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, stream, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def stream(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def stream_destroy(result, stream, *, loc=None, ip=None) -> _ods_ir.Value:
  return StreamDestroyOp(result=result, stream=stream, loc=loc, ip=ip).result

@_ods_cext.register_operation(_Dialect)
class StreamEndCaptureOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.stream.end_capture"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, graph, stream, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(stream))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    results.append(graph)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def stream(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

  @builtins.property
  def graph(self):
    return self.operation.results[1]

def stream_end_capture(result, graph, stream, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return StreamEndCaptureOp(result=result, graph=graph, stream=stream, loc=loc, ip=ip).results

@_ods_cext.register_operation(_Dialect)
class StreamSynchronizeOp(_ods_ir.OpView):
  OPERATION_NAME = "cuda.stream.synchronize"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, stream, *, event=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(stream))
    if event is not None: operands.append(_get_op_result_or_value(event))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def stream(self):
    return self.operation.operands[0]

  @builtins.property
  def event(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def stream_synchronize(result, stream, *, event=None, loc=None, ip=None) -> _ods_ir.Value:
  return StreamSynchronizeOp(result=result, stream=stream, event=event, loc=loc, ip=ip).result
